### ISSUE TITLE
Fullscreen possible?

### ISSUE THREAD

**Issue by InanimateCrbnRod** [devwolf75/capture-card-viewer-tauri#1]
Hi! This app is excellent. I have a single PC streaming setup and I'm trying to play as I capture with my ripsaw HD. OBS is a little choppy in fullscreen preview, but this app is flawless, only issue is that I can't fullscreen this app. is there a keyboard shortcut or something? Thanks!

**Comment by devwolf75** [comment]
Hi, sorry for the late reply. Let me see what I can do about it. Any contribution is open. :)

**Comment by devwolf75** [comment]
Full screen added. 🥳
